CREATE TABLE Chat_Room(
    id int generated by default as identity,
    first_user_id int,
    second_user_id int,
    CONSTRAINT PK_TwoUserIds PRIMARY KEY (first_user_id, second_user_id),
    FOREIGN KEY (first_user_id) REFERENCES Users(id),
    FOREIGN KEY (second_user_id) REFERENCES Users(id)
);