ALTER TABLE Chat_Room ADD CONSTRAINT UC_Chat_Room_id UNIQUE (id);

CREATE TABLE Chat_Message(
    id int generated by default as identity primary key,
    chat_id int,
    content varchar(255),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (chat_id) REFERENCES Chat_Room(id)
);